config/routes.rb
Rails.application.routes.draw do

  root to: 'users#sign_in'

  resources :recipes do
    resources :comments
  end
  get '/converter', to: 'pages#converter'
  get '/temp', to: 'pages#temp'
  get '/user/recipes', to: 'users#index'
  # could also nest recipes under users to have full CRUD functionality.
  # Check out shallow nesting as well -http://edgeguides.rubyonrails.org/routing.html#shallow-nesting
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user # but only sometimes, right? see comment in config/routes.rb

  def self.search(query)
  # EXCELLENT use of model method!!!!
  # where(:title, query) -> This would return an exact match of the query
  where("ingredients ilike ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  has_secure_password
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :authenticate  # if they try to go to anywhere in the website, except for user actions, there redirected to sign_in page
    # excellent code comments!

  private
  def authenticate
    if !session[:user]
      redirect_to "/sign_in"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def index
    @recipe = Recipe.find(params[:recipe_id])
    @comments = @recipe.comments.order(created_at: :desc)
  end
  def show
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
  end
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.new
  end
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.create!(comment_params)
    redirect_to recipe_comments_path(@recipe)
  end
  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
  end
  def update
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to recipe_comments_path(@recipe, @comment)
  end
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to recipe_comments_path(@recipe)
  end
  private
  def comment_params
    params.require(:comment).permit(:content, :recipe_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def converter

  end
  def temp

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    if params[:search]
      @recipes = Recipe.search(params[:search]).order(created_at: :desc)
    else
    @recipes = Recipe.all.order(created_at: :desc)
    end
  end
  def show
    @recipe = Recipe.find(params[:id])

  end
  def new
    @recipe = Recipe.new
  end
  def create
    @user = User.find(session[:user]["id"])
    @recipe = @user.recipes.create!(recipe_params)
    redirect_to recipe_path(@recipe)
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end
private
def recipe_params
  params.require(:recipe).permit(:title, :directions, :ingredients, :photo_url, :user_id, :notes)
  # I recommend removing the :user_id from your strong params. In your create action, you are finding the
  # user based on session variables. You can do the same thing for update.
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate

  def index
      @user = User.find(session[:user]["id"])
      @recipes = @user.recipes.order(created_at: :asc)
  end
  def show
      @recipe = Recipe.find(params[:id])
  end
  def sign_up
  end
  def sign_up!
    user = User.new(
      username: params[:username],
      useremail: params[:useremail],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    flash[:notice] = message
    redirect_to action: :sign_in
  end
  def sign_in
  end
  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])  # need to better understand this line
      message = "Your password's wrong!"
    else
      message = "You're signed in, #{@user.username}!"
      cookies[:username] = {
        value: @user.username,
        expires: 3.years.from_now
      }
      session[:user] = @user
    end
    flash[:notice] = message
    redirect_to recipes_path
  end
   def sign_out
     reset_session
     flash[:notice] = "Signed out, happy cooking!!!"
     redirect_to root_url
   end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/views/comments/_form.html.erb
<%= form_for [@recipe, @comment] do |f| %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit :class => 'btn' %>

  <% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render partial: "form" %>




<button class="btn">
  <%= link_to "Delete", recipe_comment_path(@recipe, @comment), method: :delete %>
</button>

app/views/comments/index.html.erb
<h2>View Comments</h2>

<h3><%= @recipe.title %></h3>
<div class="container_show">
  <div class="child_show">
    <p>Ingredients: <%= simple_format(@recipe.ingredients) %></p>
  </div>
  <div class="child_show">
      <%= image_tag @recipe.photo_url , :class => 'photo_size' %>
  </div>
</div>
<div class="prep">
  <h4>Preparation:</h4>
  <p><%= simple_format(@recipe.directions) %></p>
</div>

<h4>Comments:</h4>
<% @comments.each do |comment| %>
  <div class="comment">
    <p>--<%= comment.content %></p>
    <p><%= time_ago_in_words comment.created_at %> ago <%= link_to 'Edit or Delete Comment' , edit_recipe_comment_path(@recipe, comment) %></p>

  </div>
<% end %>

<%= link_to "Add a Comment" , new_recipe_comment_path(@recipe) %>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render partial: "form" %>

app/views/comments/show.html.erb
<h3><%= @recipe.title %></h3>
<div class="container_show">
  <div class="child_show">
      <%= image_tag @recipe.photo_url %>
  </div>
  <div class="child_show">
      <h4>Ingredients: </h4>
      <p><%= simple_format(@recipe.ingredients) %></p>
  </div>
</div>
<h4>Preparation:</h4>
<p><%= simple_format(@recipe.directions) %></p>

<div class="comment">
  <p>Comment: <%= @comment.content %></p>
  <p><%= @comment.created_at %></p>
</div>


<%= link_to "Comments" ,  new_recipe_comment_path(@recipe)  %>
<%= link_to "Edit Comment" , edit_recipe_comment_path(@recipe, @comment) %>
<%= link_to "Delete", recipe_comment_path(@recipe,@comment), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeBox</title>
  <link href='https://fonts.googleapis.com/css?family=Dosis:600' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1 class="logo">Recipe Box</h1>
    <nav class="main_nav">
    <% if session[:user] %>
      <!-- could also use a current_user helper like devise -->
      <%= link_to "All Recipes" , recipes_path %>
      <%= link_to "User Recipes" , user_recipes_path %>
      <%= link_to "Create New Recipe" , new_recipe_path(@recipe) %>
      <%= link_to "Temps" , temp_path %>
      <%= link_to "Converter" , converter_path %>
      <!-- can you think of a way to show to the user which page (s)he is currently on? -->
      <a href="/sign_out"><%= session[:user]["username"] %>: sign out</a>
    <% else %>
      <a href="/sign_in">Sign in</a>
      <a href="/sign_up">Sign up</a>
    <% end %>
    </nav>
  </header>
  <h2 class="flash"><%= flash[:notice] %></h2>
<%= yield %>

</body>
</html>

app/views/pages/converter.html.erb
<h2>Coming Soon...currently under construction</h2>

app/views/pages/temp.html.erb
  <ul class="temp_nav">
    <li id="poultry">Poultry</li>
    <li id="beef">Beef</li>
    <li id="pork">Pork</li>
    <li id="lamb">Lamb</li>
  </ul>

<div class="container_index">

  <div class="poultry hide">
    <h3>Poultry</h3>
    <h4>Whole Bird, Thighs, Legs, Wings, Ground Poultry</h4>
    <p>USDA Guidelines (before resting): 165 degrees</p>
    <p>Professional Kitchens (before resting): 165 degrees</p>
    <h4>Boneless Chicken Breasts</h4>
    <p>USDA Guidelines (before resting): 165 degrees</p>
    <p>Professional Kitchens (before resting): 160 degrees</p>
  </div>

  <div class="temps_hide beef hide">
    <h3>Beef</h3>
    <h4>Rare</h4>
    <p>USDA Guidelines (before resting): n/a</p>
    <p>Professional Kitchens (before resting): 115 degrees</p>
    <h4>Medium-Rare</h4>
    <p>USDA Guidelines (before resting): 145 degrees</p>
    <p>Professional Kitchens (before resting): 120 degrees</p>
    <h4>Medium</h4>
    <p>USDA Guidelines (before resting): 160 degrees</p>
    <p>Professional Kitchens (before resting): 140 degrees</p>
    <h4>Medium-Well</h4>
    <p>USDA Guidelines (before resting): n/a</p>
    <p>Professional Kitchens (before resting): 150 degrees</p>
  </div>

  <div class="temps_hide pork hide">
    <h3>Pork</h3>
    <h4>Medium</h4>
    <p>USDA Guidelines (before resting): 160 degrees</p>
    <p>Professional Kitchens (before resting): 145 degrees</p>
    <h4>Well-Done</h4>
    <p>USDA Guidelines (before resting): 170 degrees</p>
    <p>Professional Kitchens (before resting): 160 degrees</p>
  </div>

  <div class="temps_hide lamb hide">
    <h3>Lamb</h3>
    <h4>Rare</h4>
    <p>USDA Guidelines (before resting): n/a</p>
    <p>Professional Kitchens (before resting): 115 degrees</p>
    <h4>Medium-Rare</h4>
    <p>USDA Guidelines (before resting): 145 degrees</p>
    <p>Professional Kitchens (before resting): 130 degrees</p>
    <h4>Medium</h4>
    <p>USDA Guidelines (before resting): 160 degrees</p>
    <p>Professional Kitchens (before resting): 140 degrees</p>
    <h4>Medium-Well</h4>
    <p>USDA Guidelines (before resting): n/a</p>
    <p>Professional Kitchens (before resting): 150 degrees</p>
  </div>

</div>

app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => {:class => 'new_form'} do |f| %>
<!-- nice use of class in form_for!! -->

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :ingredients %>
  <%= f.text_area :ingredients  %>

  <%= f.label :directions %>
  <%= f.text_area :directions  %>


  <%= f.submit %>

  <% end %>

app/views/recipes/edit.html.erb
<h2>Edit Recipe</h2>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<%= form_tag(recipes_path, :method => "get", id: "search-form" ) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Ingredients to find Recipes" %>
      <button class="btn" type="submit">Search</button>
<% end %>

<div class="container_index">
  <% @recipes.each do |recipe| %>
  <div class="recipe">
      <h3><%= recipe.title %></h3>
      <%= link_to image_tag( recipe.photo_url , {:alt=>"#{recipe.title}"}), recipe_path(recipe) %>
  </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h2>New Recipe</h2>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h3><%= @recipe.title %></h3>
<div class="container_show">
  <div class="child_show">
      <h4>Ingredients:</h4>
      <p><%= simple_format(@recipe.ingredients) %></p>
  </div>
  <div class="child_show">
      <%= image_tag @recipe.photo_url %>
  </div>
</div>


<div class="prep">
  <h4>Preparation:</h4>
  <p><%= simple_format(@recipe.directions) %></p>


  <%= link_to 'View comments' , recipe_comments_path(@recipe) %>
  <%= link_to "Add a Comment" ,  new_recipe_comment_path(@recipe)  %>
  <%= link_to "Edit Recipe" , edit_recipe_path(@recipe) %>
  <%= link_to "Delete", recipe_path(@recipe), method: :delete %>
</div>

app/views/users/index.html.erb
<h2><%= @user.username %>'s Recipes</h2>
<!-- this feels like a "recipes" view more than a "users" view -->


<div class="container_index">
<% @recipes.each do |recipe| %>
<div class="recipe">
    <h3><%= recipe.title %></h3>
    <%= link_to image_tag( recipe.photo_url , {:alt=>"#{recipe.title}"}), recipe_path(recipe) %>
</div>
<% end %>

app/views/users/show.html.erb
<h3><%= @recipe.title %></h3>
<div class="container_flex">
  <div class="child_flex">
      <%= image_tag @recipe.photo_url %>
  </div>
  <div class="child_flex">
      <p>Ingredients: <%= @recipe.ingredients %></p>
  </div>
</div>
<p>Preparation: <%= @recipe.directions %></p>

<%= link_to "Home" , recipes_path %>
<%= link_to 'View comments' , recipe_comments_path(@recipe) %>
<%= link_to "Add a Comment" ,  new_recipe_comment_path(@recipe)  %>
<%= link_to "Edit Recipe" , edit_recipe_path(@recipe) %>
<%= link_to "Delete", recipe_path(@recipe), method: :delete %>

app/views/users/sign_in.html.erb
<h2>Welcome to Recipe Box</h2>
<h2>Sign in</h2>
<%= form_tag sign_in_path , method: :post , :class => 'sign_form' do %>
  <input type="text" name="username" placeholder="username" value="<%= cookies[:username] %>" />
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>

app/views/users/sign_up.html.erb
<h2>Sign up</h2>
<%= form_tag sign_up_path , method: :post, :class => 'sign_form' do %>
  <input type="text" name="username" placeholder="username" />
  <input type="text" name="useremail" placeholder="useremail" />
  <input type="password" name="password" placeholder="password" />
  <input type="password" name="password_confirmation" placeholder="password again" />
  <input type="submit" value="Sign up" />
<% end %>